# Name(s)
**PUT YOUR FULL NAME(S) HERE**

**Instructions:** This is an individual assignment, but you may discuss your code with your neighbors.

# Python and NumPy

While other IDEs exist for Python development and for data science related activities, one of the most popular environments is Jupyter Notebooks.

This lab is not intended to teach you everything you will use in this course. Instead, it is designed to give you exposure to some critical components from NumPy that we will rely upon routinely.

## Exercise 0
Please read and reference the following as your progress through this course. 

* [What is the Jupyter Notebook?](https://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/What%20is%20the%20Jupyter%20Notebook.ipynb#)
* [Notebook Tutorial](https://www.datacamp.com/community/tutorials/tutorial-jupyter-notebook)
* [Notebook Basics](https://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/Notebook%20Basics.ipynb)

**In the space provided below, what are three things that still remain unclear or need further explanation?**

How efficient is the python interpreter in a notebook, compared to using python in a cli? how does jupyter notebook handle version changes in python? do notebooks support other languages?

## Exercises 1-7
For the following exercises please read the Python appendix in the Marsland textbook and answer problems A.1-A.7 in the space provided below.

## Exercise 1

In [14]:
# YOUR SOLUTION HERE
a = np.ones((6,4)) * 2
print(a)

[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]


## Exercise 2

In [11]:
# YOUR SOLUTION HERE
import numpy as np
b = np.ones((6, 4)) + (np.eye(6, 4) * 2)
print(b)


[[3. 1. 1. 1.]
 [1. 3. 1. 1.]
 [1. 1. 3. 1.]
 [1. 1. 1. 3.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## Exercise 3

## Exercise 4

In [16]:
print(np.dot(np.transpose(a), b))
print(np.dot(a,np.transpose(b)))
# transposing an array makes it a completely different array, causing different operations for each cell

[[3. 1. 1. 1. 1. 1.]
 [1. 3. 1. 1. 1. 1.]
 [1. 1. 3. 1. 1. 1.]
 [1. 1. 1. 3. 1. 1.]]
[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]
[[12. 12. 12. 12.  8.  8.]
 [12. 12. 12. 12.  8.  8.]
 [12. 12. 12. 12.  8.  8.]
 [12. 12. 12. 12.  8.  8.]
 [12. 12. 12. 12.  8.  8.]
 [12. 12. 12. 12.  8.  8.]]


## Exercise 5

In [20]:
def f():
  print("this is my function")
f()

this is my function


## Exercise 6

In [34]:
def rand():
    c = np.random.randint(0,10,(5, 5))
    print(c)
    print("sum: " + str(np.sum(c)))
    print("mean: " + str(np.sum(c)/25))
rand()
rand()
rand()

[[0 6 0 7 9]
 [3 4 3 7 3]
 [4 9 4 8 3]
 [1 3 7 4 1]
 [6 3 4 0 3]]
sum: 102
mean: 4.08
[[6 2 2 0 7]
 [0 1 2 4 2]
 [7 6 2 3 1]
 [4 5 2 2 9]
 [7 4 2 2 7]]
sum: 89
mean: 3.56
[[7 2 6 2 2]
 [8 4 8 6 7]
 [7 9 3 9 8]
 [5 7 0 0 1]
 [6 3 0 4 0]]
sum: 114
mean: 4.56


## Exercise 7

In [46]:
def count_one(arr):
    count = 0;
    for a in range(len(arr)):
        if(arr[a] == 1):
            count += 1
    return count

def count_one_better(arr):
    c = np.where(arr == 1, arr, 0)
    return np.sum(c)
    
print(count_one_better(np.arange(10)))
print(count_one(np.arange(10)))

1
1


## Excercises 8-???
While the Marsland book avoids using another popular package called Pandas, we will use it at times throughout this course. Please read and study [10 minutes to Pandas](https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html) before proceeding to any of the exercises below.

## Exercise 8
Repeat exercise A.1 from Marsland, but create a Pandas DataFrame instead of a NumPy array.

In [ ]:
# YOUR SOLUTION HERE

## Exercise 9
Repeat exercise A.2 using a DataFrame instead.

In [ ]:
# YOUR SOLUTION HERE

## Exercise 10
Repeat exercise A.3 using DataFrames instead.

In [ ]:
# YOUR SOLUTION HERE

## Exercise 11
Repeat exercise A.7 using a dataframe.

In [ ]:
# YOUR SOLUTION HERE

## Exercises 12-14
Now let's look at a real dataset, and talk about ``.loc``. For this exercise, we will use the popular Titanic dataset from Kaggle. Here is some sample code to read it into a dataframe.

In [ ]:
titanic_df = pd.read_csv(
    "https://raw.githubusercontent.com/dlsun/data-science-book/master/data/titanic.csv"
)
titanic_df

Notice how we have nice headers and mixed datatypes? That is one of the reasons we might use Pandas. Please refresh your memory by looking at the 10 minutes to Pandas again, but then answer the following.

## Exercise 12
How do you select the ``name`` column without using .iloc?

In [ ]:
## YOUR SOLUTION HERE

## Exercise 13
After setting the index to ``sex``, how do you select all passengers that are ``female``? And how many female passengers are there?

In [ ]:
## YOUR SOLUTION HERE
titanic_df.set_index('sex',inplace=True)

## Exercise 14
How do you reset the index?

In [ ]:
## YOUR SOLUTION HERE